### ISSUE TITLE
Whether TEtranscripts can calculate TE expression level of transcripts (NOT Gene)?

### ISSUE THREAD

**Issue by xflicsu** [mhammell-laboratory/tetoolkit#13]
As the title asked. 
Whether TEtranscripts can calculate TE expression level of transcripts (NOT Gene)?

**Comment by yingjin07** [comment]
The current version only provides TE expression on element (subfamily) level not each insertions (transcripts).

**Comment by xflicsu** [comment]
Is it reasonable to replace gene_id name to transcript_id name in rmsk_TE.gtf file?
And then count the reads located in each insertions (transcripts).
As the gtf file shows us that one element (subfamily) containing several loci.
It is not clear to get the expression of one specific insertions.

**Comment by yingjin07** [comment]
The reason that we don't output transcript level abundance is that we don't think that the current methods and the technology can give reliable/accurate estimation.
