### ISSUE TITLE
Where can I download the GTF file for hg38?

### ISSUE THREAD

**Issue by insidemymind** [mhammell-laboratory/tetoolkit#14]
Hi,
I want to try this software but the GTF and test files are all gone on this link (http://labshare.cshl.edu/shares/mhammelllab/www-data/TEToolkit/) as shown in your manual page. Does it mean there is no more support for this software?

**Comment by olivertam** [comment]
Hi,
We are looking into why the files are not visible via that link, and will get back to you as soon as possible.
Thanks.

**Comment by yingjin07** [comment]
The files are available now.

**Comment by insidemymind** [comment]
They are back now. Thanks for such swift response!
