### ISSUE TITLE
How long to build TE index from hg19_rmsk_TE.gtf?

### ISSUE THREAD

**Issue by dtsgx** [mhammell-laboratory/tetoolkit#15]
INFO  @ Fri, 17 Nov 2017 13:52:22: Processing GTF files ...
 
INFO  @ Fri, 17 Nov 2017 13:52:22: Building gene index .......
 
100000 GTF lines processed.
200000 GTF lines processed.
300000 GTF lines processed.
400000 GTF lines processed.
INFO  @ Fri, 17 Nov 2017 13:53:16: Done building gene index ......
 
INFO  @ Fri, 17 Nov 2017 13:54:15: 
Building TE index .......

It seems to be stuck in this step. Is this normal?

@olivertam @yingjin07

**Comment by yingjin07** [comment]
It usually takes about 10 minutes.

**Comment by dtsgx** [comment]
Thank you. But it had been building TE index for over 12h, what't the problem?

**Comment by dtsgx** [comment]
Thank you. But it had been building TE index for over 12h and still not done. What't the problem?

**Comment by olivertam** [comment]
Hi. 
What genome build are you using? 
Was the TE GTF file obtained from the FTP site, or was it user-generated?
You are right. It should not be taking this long.
Thanks

**Comment by dtsgx** [comment]
TE GTF files were downloaded from your FTP. TEtranscripts was ran on a 4 GB RAM virtual machine. Is it too small to run TEtranscripts? Thanks.

**Comment by olivertam** [comment]
Hi.
Given the long time that the TE index is taking, I am suspecting that 4 GB of RAM on the virtual machine (which is probably running something else) might be insufficient. We have typically used 15Gb of RAM, and typically prefer at least 9Gb dedicated to the task (my recollection is that the tool could use up to 8.4 Gb for human data, largely due to the TE index).
Hope this is helpful.
Thanks.

**Comment by yingjin07** [comment]
Hi,

Yes. 4GB of memory is not sufficient to keep both gene and TE indices and intermediate data structures for storing multi-reads. Please refer to the paper Figure 6 for running time and memory usage of different sample sizes.

Best,
Ying

Ying Jin PhD

Computational Science Manager
Bioinformatics Shared Resources
Cold Spring Harbor Lab
516-367-5190
yjin at cshl dot edu
________________________________
