### ISSUE TITLE
Question about the alignments preparation

### ISSUE THREAD

**Issue by vasilislenis** [mhammell-laboratory/tetoolkit#16]
Hello TEtranscripts group,

My question is not in the main part of TEtranscripts process (it works fine since you helped me last time, and thank you for that), it is in the alignments preparation.
I am trying to find if there is a significant DE in transposable elements (L1) in my samples but unfortunately, I didn't find any, so far. So, I was thinking the case that my alignments aren't so sensitive. I have single reads and I have tried bowtie and BWA-MEM so far. In your paper you describe that you used STAR with -outFilterMultimapNmax = 100 and -winAnchorMultimapNmax = 100. The STAR command includes the annotation file (gtf) so, I was wondering if I have to prepare two BAM alignment files for each sample. One by using the genes annotation and another one for the repeats. After that, I am thinking to merge them into one alignment file and feed the TEtranscripts.
Is it sound reasonable this approach?
Is it possible to provide me a sample of the alignment commands that you were used?

Thank you very much in advance,
Vasilis.

**Comment by olivertam** [comment]
Hi Vasilis,

We only use the gene annotation GTF during STAR mapping (we usually build the index with it), as the TE GTF treats each TE instance as an unspliced unit, and thus not needed to align splice junction reads. We haven't really used Bowtie (I'm assuming Bowtie2) or BWA-MEM for RNA-seq alignment, as they are not specifically designed for this application.
These are the STAR parameters that we have used:
```bash
--readFilesCommand 'zcat -fc' 
--outSAMattributes Standard 
--outSAMunmapped None
--outFilterMultimapNmax  100
--winAnchorMultiapNmax 100
--outFilterMismatchNoverLmax 0.04 
--outFilterType BySJout 
--outStd SAM
```
Please note that STAR is very memory-intensive (around 30G for aligning to hg19 + refSeq GTF).
Hopefully this helps.
Thanks.

**Comment by vasilislenis** [comment]
@olivertam Thank you very much, Oliver.
I will give them a shot!

**Comment by vasilislenis** [comment]
Hi Oliver,

I am really sorry for bothering you again, but I have another question which it is more relative with the process than with a technical aspect (this is the reason that I haven't opened a new conversation topic). I used STAR to realign my reads based on your parameters and the results were pretty similar with BWA's alignments. I haven't found any significant change in L1 elements. The thing that I believe that I am missing, is the way that TEtranscripts handles the transposable elements. For example, I know that the genes exist in all the samples so, there are counts for each one and based on this the pvalue is calculated. On the other hand, there is no warranty that the L1s exists in also the sample, so how the calculations are being made? Are the elements that are not present in all the samples excluded?
I am really sorry for annoying you with such questions, but I am a little bit confused.

Many thanks,
Vasilis.

**Comment by olivertam** [comment]
Hi Vasilis,

Actually, I would argue that not all genes exist in every sample, and that there will be genes where there would not be counts (and would be zero). The differential expression calculation is done by DESeq (the methodology of which is described in more detail [here](https://bioconductor.org/packages/release/bioc/html/DESeq.html)). It is designed to handle "zero" values in gene/TE expression in one or both of the samples. To determine if the absence of L1 is the reason why they are not seen as significant, you can extract all the L1 elements from the gene_TE_analysis.txt file, and look at the BaseMean (column 2), log2FC (column 3), raw p-value (column 6) and FDR (column 7). This should indicate whether the TE was not detected (column 2 would be lower than others, or almost zero), the fold change is not that strong (column 3 is close to 0), or the raw p-value (either due to variations within replicate, or absence of replicates) being not significant before correction to FDR (column 6 is >0.05, for example).

Let me know if that is more helpful.
Thanks.

**Comment by vasilislenis** [comment]
Hello Oliver, 

Thank you very much for your very helpful reply. However, I would like to have your help because I am a little bit confused.

I have the following 2 examples:


id      baseMean        baseMeanA       baseMeanB       foldChange      log2FoldChange  pval    padj
uc001boo.1      1465.28838778992        2302.24188420212        628.334891377714        0.272923056299739       -1.87343381751887       4.10173437092023e-12    8.75788650430983e-09


id      baseMean        baseMeanA       baseMeanB       foldChange      log2FoldChange  pval    padj
L1HS:L1:LINE    29832.6744268905        27583.7579089232        32081.5909448578        1.1630609234168 0.217926669991897       0.355069665915235       1

The first (gene) is characterised as significant but the second one (L1) as not.

I can see that the baseMean (column 2) in the L1 case is big, the log2FC (column 6) is not close to 0 but the raw p-value and the FDR are not good.

I understand that the difference between the 2 means (baseMeanA and baseMeanB, I believe that these are the means for the treatment and control samples) is smaller in the gene case to the L1. Is it the reason that the pvalue shows that it is not significant?

Thank you very much and I am really sorry for my naive questions.
Vasilis.

**Comment by olivertam** [comment]
Hi Vasilis,

Looking at the gene, there is a fold change of 0.27 (almost a quarter of the "control"). My assumption is that this is greater than the variation within replicates of sample A or sample B, and thus DESeq considers it significantly different. You are correct that the read count is higher in the L1HS sample, but the fold change is much smaller (1.16, meaning that there is an approximately 16% increase). What is not clear from the values show is the variation within each of the replicates (which DESeq accounts for if there are replicates), meaning that even within samples (e.g. control), there might be sufficient variation in L1HS expression that makes them overlap with the other samples (e.g. treatment) This might be why DESeq considers L1HS not significantly different.
Hope this is helpful.
Thanks.
