### ISSUE TITLE
Deal with samples in multiple stages

### ISSUE THREAD

**Issue by xinl22** [mhammell-laboratory/tetoolkit#18]
Hi, In the manual of TEtranscript it requires -c -t to specify the control/treatment. But my samples are from multiple stages and I just hope to get TE expression of different stages. What should I do? 
Thanks.

**Comment by olivertam** [comment]
Hi. Are you trying to compare gene/TE expression at different stages? You can specify your "treatment" and "control" as the stages that you want to compare (e.g. day 2 vs day 0). 

There is another approach that might be helpful, but I apologize if I get a little long-winded in my explanation.
Let's say you have four different stages/timepoints with two replicates per timepoint: Day 1, Day 5, Day 7 and Day 14. You might want to compare across different days. You can  run TEtranscripts multiple times, using a different set as treatment and control (e.g. Day14 as treatment, Day 7 as control; Day 7 as treatment, Day 1 as control). This would require the least amount of downstream manipulation (if you're just interested in getting differentially expressed TE/genes), but potentially tedious as you are counting the libraries multiple times (in the above example, you would count the Day 7 samples twice).

The alternative is to generate the counts table (e.g. gene & TE count) for each of the timepoints by running TEtranscripts non-redundantly. In the above example (2 replicates for Day 1, 5, 7 and 10), you can run TEtranscripts with `-t` Day 5 and `-c` Day 1, and generate a count table ([name].cntTable) where the first column is the gene/TE name, columns 2 & 3 are the two replicates for Day 5, and columns 4 & 5 are the two replicates for Day 1. You can then run TEtranscripts using `-t` Day 10 and `-c` Day 7, and again obtain a count table where columns 2 & 3 are now the replicates for Day 10, and columns 4 & 5 are replicates for Day 7. You can either join the two count tables using the `join` command in bash to get an overall table, or you can cut & join different timepoints by using `cut` and `join`. E.g. if you want to compare Day 1 and Day 10, you `cut` column 1 (gene/TE name), 4 & 5 from the first counts table, and column 1 (gene/TE name), 2 & 3 from the second counts table, and `join` them (using the gene/TE name as the key) to make the count table for Day 1 & Day 10. You can then use that for differential analysis, or whatever downstream analysis you need. The downside of this approach is that you would need to generate your own script/commands for differential analysis, but it gives you more flexibility.

Hope this is helpful. Please let me know if anything is unclear or if I did not answer your question.
Thanks.

**Comment by xinl22** [comment]
@olivertam I got it! Thanks for your detailed explanation.

**Comment by xinl22** [comment]
@olivertam Hi Oliver, I randomly picked two my samples as a test. But it seems that I failed to get any TE counts. I used STAR for mapping and used recommended parameters in another issue

STAR diameters:
` --readFilesCommand zcat `
`--outSAMattributes Standard `
`--outSAMunmapped None `
`--outFilterMultimapNmax  100 `
`--outFilterMismatchNoverLmax 0.04 `
`--outFilterType BySJout `
`--outStd SAM `
`--winAnchorMultimapNmax 100 `
`--limitOutSJcollapsed 2000000 `
`--clip5pNbases 12 `
Finally get two sam files.

 TEtranscript diameters:
`# treatment files = ['Day7.sam']`
`# control files = ['Day0.sam']`
`# GTF file = /public/home/Drosophila_melanogaster.BDGP6.91.chr.gtf `
`# TE file = /public/home/dm6_rmsk_TE.gtf `
`# multi-mapper mode = multi `
`# stranded = no`
`# normalization = TC (rpm: Reads Per Million mapped; quant: Quantile normalization)`
`# FDR cutoff = 5.00e-02`
`# fold-change cutoff =  1.00`
`# read count cutoff = 1`
`# number of iteration = 10`
`# Alignments grouped by read ID = True`

It turns out:
INFO  @ Sun, 04 Mar 2018 23:33:00: Processing GTF files ...
INFO  @ Sun, 04 Mar 2018 23:33:00: Building gene index .......
100000 GTF lines processed.
INFO  @ Sun, 04 Mar 2018 23:33:51: Done building gene index ......
INFO  @ Sun, 04 Mar 2018 23:34:01: 
Building TE index .......
INFO  @ Sun, 04 Mar 2018 23:34:07: Done building TE index ......
INFO  @ Sun, 04 Mar 2018 23:34:07: 
Reading sample files ...
uniq te counts = 0.0 
.......start iterative optimization ..........
TE counts total 0.0
Gene counts total 14761092.414
In library Day7.sam:
Total annotated reads = 14761092.414
Total non-uniquely mapped reads = 473380
Total unannotated reads = 1188245
uniq te counts = 0.0 
.......start iterative optimization ..........
TE counts total 0.0
Gene counts total 13551622.5596

In library Day0.sam:
Total annotated reads = 13551622.5596
Total non-uniquely mapped reads = 266630
Total unannotated reads = 1355478
INFO  @ Mon, 05 Mar 2018 00:40:21: Finished processing sample files 
INFO  @ Mon, 05 Mar 2018 00:40:21: Generating counts table 
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
Error in library(DESeq, quietly = T) : there is no package called 'DESeq'
Execution halted
INFO  @ Mon, 05 Mar 2018 00:40:22: Done

**Comment by olivertam** [comment]
Hi. It's unclear whether you used the `--format SAM` option in your command line, since TEtranscripts defaults to reading a BAM file if that option is not invoked.
I'd be happy to take a closer look at the SAM files if that doesn't solve the issue. You can contact me at tam at cshl dot edu. Thanks.

**Comment by olivertam** [comment]
Thank you for sending the SAM files. It appears that the reason why the TE annotations were not being found is because of the chromosome name used in the alignment process. The TE GTF file available for download uses the UCSC chromosomal nomenclature (e.g. chr2L, chr2R). The SAM files that you provided shows alignment to the Flybase/BDGP chromosomal nomenclature (e.g. 2L, 3L), and thus the reads would annotate to the gene GTF (which presumably uses the Flybase nomenclature), but not to the TE GTF (using the UCSC nomenclature). 
A version of the dm6 TE GTF has now been generated to use the Flybase/BDGP chromosomal nomenclature, and should be available for download. Hopefully this should resolve the issue.
Thanks for letting us know of this quirk.

**Comment by olivertam** [comment]
To convert between the UCSC and Flybase chromsome IDs, I used the instructions on this google group thread: https://groups.google.com/a/soe.ucsc.edu/forum/#!topic/genome/-dUcyIoj_vg

In essence, I obtained the file described in the post
(GCA_000001215.4_Release_6_plus_ISO1_MT_assembly_report.txt), and compared
column 1 (which is the FlyBase nomenclature), with columns 3 & 5 (which
UCSC uses for their chromosome nomenclature). I then followed the
instructions that they described to get the UCSC chromosome name, and
converted them to the corresponding FlyBase chromosome.
