### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by gabciamm** [mhammell-laboratory/tetoolkit#19]
Hi,
 I have a problem with index building for TE.gtf.

TEtranscripts --sortByPos --format BAM --mode multi -t /media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-P-1_sorted.bam /media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-P-2_sorted.bam /media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-P-3_sorted.bam -c /media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-B-1_sorted.bam /media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-B-2_sorted.bam /media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-B-3_sorted.bam --GTF /media/gabi/Maxtor/Marchew_Kallus_RNAseq/TEtool/genes_input3.gtf --TE /media/gabi/Maxtor/Marchew_Kallus_RNAseq/TEtool/rep3.gtf --project DH
INFO  @ Tue, 06 Mar 2018 16:30:41: 
# ARGUMENTS LIST:
# name = DH
# treatment files = ['/media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-P-1_sorted.bam', '/media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-P-2_sorted.bam', '/media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-P-3_sorted.bam']
# control files = ['/media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-B-1_sorted.bam', '/media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-B-2_sorted.bam', '/media/gabi/Maxtor/Marchew_Kallus_RNAseq/bam/DH-B-3_sorted.bam']
# GTF file = /media/gabi/Maxtor/Marchew_Kallus_RNAseq/TEtool/genes_input3.gtf 
# TE file = /media/gabi/Maxtor/Marchew_Kallus_RNAseq/TEtool/rep3.gtf 
# multi-mapper mode = multi 
# stranded = yes 
# normalization = DESeq_default (rpm: Reads Per Million mapped; quant: Quantile normalization)
# FDR cutoff = 5.00e-02
# fold-change cutoff =  1.00
# read count cutoff = 1
# number of iteration = 10
# Alignments grouped by read ID = False

 
INFO  @ Tue, 06 Mar 2018 16:30:41: Processing GTF files ...
 
INFO  @ Tue, 06 Mar 2018 16:30:41: Building gene index .......
 
100000 GTF lines processed.
200000 GTF lines processed.
300000 GTF lines processed.
400000 GTF lines processed.
INFO  @ Tue, 06 Mar 2018 16:41:09: Done building gene index ......
 
INFO  @ Tue, 06 Mar 2018 16:41:09: 
Building TE index .......
 
chr1	blastn	exon	1	240	783.80	+	.	 gene_id "CL8*"; transcript_id "173870"; family_id "Copia"; class_id "LTR";
TE GTF format error! There is no annotation at line 1.
Error in building gene/TE index

**Comment by olivertam** [comment]
Hi,
Could you double-check that the first 9 columns in the TE GTF file are separated by tabs, and the values in column 9 are separated by spaces? 
Thanks.

**Comment by gabciamm** [comment]
Hi,
Thank you for reply.
Yes they are tab separated and spaces are in 9 column. So there is be some
other problem... Actually I had problems with my TE file from very
beginning - starting from gff3 to gtf conversion. I will be very grateful
if you could help me to process my TE gff files to adjust them to the
Tetranscripts tool  requirements.
Best,

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-06 18:14 GMT+01:00 Oliver Tam <notifications@github.com>:

**Comment by olivertam** [comment]
Hi,
If you would like to send me the TE GFF/GTF file that you have generated, I can certainly take a look.
You can contact me directly at tam at cshl dot edu.
Thanks.

**Comment by gabciamm** [comment]
OK, Thanks
