### ISSUE TITLE
Lots of unannotated reads

### ISSUE THREAD

**Issue by MonkeySylvia** [mhammell-laboratory/tetoolkit#22]
Hi,
I'm counting gene/TE expression in zebrafish. I used hisat2 to map my reads to the genome (danRer10) and then used the bam file to run TEtranscript. I used the zebrafish gtf file provided from this website as my reference gtf. However, lots of reads are classified as 'unannotated reads'. Should I concern for this issue? Thanks!
Sylvia

my code
`nohup TEtranscripts --project first_try_tetranscripts --GTF ../../reference/danRer10_uscs.gtf --TE danRer10_repeatmasker_table_v30309.bed -c 126_B_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam 126_C_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam 126_D_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam 126_E_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam 126_F_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam -t 127_B_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam 127_C_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam 127_D_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam 127_E_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam 127_F_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam --sortByPos > first_try_tetranscripts.log.txt &`

and one of the output
`In library 126_D_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam:
Total annotated reads = 552211.594767
Total non-uniquely mapped reads = 462588
Total unannotated reads = 6343265
`

**Comment by olivertam** [comment]
Hi Sylvia,
The proportion is higher than what we usually see for other samples. What are the Gene and TE counts for those libraries? I noticed that you are using a TE BED file (or at least a file with the BED extension) rather than a GTF file. Not sure if that makes any difference.
Thanks

**Comment by MonkeySylvia** [comment]
Hi Oliver,
My library is stranded as a normal Illumina library. Gene counts for that sample is 134302 and 414029 for TEs. And sorry, I think I provided the wrong command  for my TE bed file, I actually used the one you provided
`nohup TEtranscripts --project blas_vs_hat --GTF ../../reference/danRer10_uscs.gtf --TE danRer10_rmsk_TE.gtf`
I'm still not sure if i should concern for this issue.

**Comment by olivertam** [comment]
Hi Sylvia
Might I recommend running one treatment and one control library using the `--stranded reverse` or `--stranded no` options? Without knowing the exact RNAseq protocol used, it might be a good idea to see whether the library is reverse-stranded (especially if you're using the TruSeq kit).
That way, you can compare to the one that you ran, and see if it significantly increases the Gene counts.
Thanks.

**Comment by MonkeySylvia** [comment]
Hi Oliver, 
I tried --strand reverse and got much better annotations!
Here is my result
`In library 126_D_1.fastq.clean.fastq.clean.paired.qc.fastq.k100.sam.k100.sorted.bam:
Total annotated reads = 5914556.27231
Total non-uniquely mapped reads = 462588
Total unannotated reads = 873972
`
Thank you!!
