### ISSUE TITLE
FTP APGv4 TE GTF - Missing semi-colon in attributes field 

### ISSUE THREAD

**Issue by PriceJon** [mhammell-laboratory/tetoolkit#23]
The attribute field of the ZmAGPv4_TE.gtf file on the FTP site is a semi-colon on each line before the family_id argument. This causes an error when reading in the file. 

1	LTRharvest	exon	10263	15666	.	+	.	gene_id "RLG00027B73v400064"; transcript_id "RLG00027B73v400064" family_id "RLG00027B73v400064"; class_id "LTR";

**Comment by olivertam** [comment]
Thank you for pointing out the error. This should now be fixed, and the new file should be on our FTP site. Please let us know if you encounter other issues.
Thanks again.

**Comment by PriceJon** [comment]
No problem. Testing now but the program is nice, thanks.
