### ISSUE TITLE
Bioconda package

### ISSUE THREAD

**Issue by bgruening** [mhammell-laboratory/tetoolkit#26]
To make installation and deployment easier a [Bioconda](https://github.com/bioconda/bioconda-recipes) package would be awesome.

Thanks for you all you work!

**Comment by olivertam** [comment]
Hi,
Thank you for your feedback. We will certainly look into it.
Cheers,
Oliver

**Comment by dpryan79** [comment]
I've bumped the bioconda recipe to 2.0.3, since I needed it, so this can be closed.
