### ISSUE TITLE
S. cerevisiae TE annotation file

### ISSUE THREAD

**Issue by lfra** [mhammell-laboratory/tetoolkit#27]
Hello,

I would like to perform a TEtoolkit analysis on RNA-seq data from _S. cerevisiae_, but could not find any TE annotation file for this organism among those that you provided. Do you have any suggestions on how I can build one myself and based on which database? As far as I am aware of, there is no such neat repeat-masker resource as for the human or mouse genome.

The only "comprehensive" resource that I found is the following:
https://www.yeastgenome.org/reference/S000072465
but I am unsure how to extract this into an annotation file.

I would really appreciate your help. Thank you in advance

**Comment by olivertam** [comment]
Hi,

I took a quick look at the website, and found the [other features](https://downloads.yeastgenome.org/sequence/S288C_reference/other_features/) folder. If you download the [other_features_genomic.fasta.gz](https://downloads.yeastgenome.org/sequence/S288C_reference/other_features/other_features_genomic.fasta.gz) file, it has the genomic location of the repetitive elements in the sequence name (based on the R64-2-1 release).

What you can do is to extract the genomic location (e.g. I:707-776), the TE name (ARS102), and determine what family or class (e.g. ARS) of transposable element it belongs to (you can use the TE name), and generate a GTF file with this information. The only thing that I cannot easily determine is the genomic strand (I'm assuming that they are showing the "+" strand in the file, but that doesn't mean that the TE is on that strand). I would recommend finding the sequence of one of the TE, and comparing it with the sequence in the FASTA file to see if it's the same or reverse complement.

To generate the GTF file, follow the guidelines [here] (http://genome.ucsc.edu/FAQ/FAQformat.html#format4). The features (column 3) should be "exon". The essential attributes in the info field (column 9) are "gene_id", "transcript_id", "family_id", "class_id". Ensure the "transcript_id" is unique if possible. Also make sure the chromosome name matches the reference sequences that you are aligning to.
Here is an example line:
`I    SGB    exon    707    776    .    +    .    gene_id "ARS102"; transcript_id "ARS102"; family_id "ARS"; class_id: "ARS"`
Please let me know if there are any questions.
Thanks.

Cheers,
Oliver

**Comment by lfra** [comment]
Thank you very much! I will give it a try.
