### ISSUE TITLE
Possible README issue with outAnchorMultimapNmax

### ISSUE THREAD

**Issue by davidecarlson** [mhammell-laboratory/tetoolkit#29]
Dear Hammell lab,

Thanks for making this tool!  I'm testing it out for the first time, and it seems like it might be useful for me.

One think I noticed:

In the README, you discuss two STAR settings, outFilterMultimapNmax & outAnchorMultimapNmax.  However, based on my reading of the STAR manual (and [this ticket](https://github.com/alexdobin/STAR/issues/243) in the STAR github),  I think that the correct argument is actually winAnchorMultimapNmax.

Just wanted to let you know!
Thanks,
Dave

**Comment by yingjin07** [comment]
Thanks for your interests in TEtranscripts. It's been fixed.

**Comment by yingjin07** [comment]
Thanks for your interests in TEtranscripts. It's been fixed.

Best,
Ying

Ying Jin PhD

Computational Science Manager
Bioinformatics Shared Resources
Cold Spring Harbor Lab
516-367-5190
yjin at cshl dot edu
________________________________
