### ISSUE TITLE
TEcount vs TEtranscripts

### ISSUE THREAD

**Issue by retrogenomics** [mhammell-laboratory/tetoolkit#30]
Hi,

As I understood it, TEcount is able to do standalone counting of a single RNA-seq dataset, in a manner similar to TEtranscripts, but this allows a sort of "multithreading" by counting in parallel several samples through several instances of TEcount, right?

Thus my question is: is there an easy way to run TEtranscripts using the results of TEcount and thus skipping the counting itself, just going to the DE analysis?

Thanks in advance for your help
-Gael

PS: by the way, great update !

**Comment by yingjin07** [comment]
Hi Gael,

Thanks for interested in TEtranscripts/TEcount. TEtrascripts uses DESeq package for DE analysis, so once you have the counting output, you can just input that to DESeq package. There is a detailed user guide for running DEseq in bioconductor.

**Comment by olivertam** [comment]
Hi Gael,

You are correct about the usage of TEcount. As @yingjin07 mentioned, we use the DESeq2 package for DE analysis. 
Our typical approach is to combine multiple count tables generated by TEcount into a single combined count table (We like to use the `multijoin.pl` tool provided by @agordon, available [here](https://github.com/agordon/bin_scripts/tree/master/scripts)). We then load the count table and run DESeq2 from within R.

Here is an example R script that you can use:
```
data <- read.table("combined.cntTable",header=T,row.names=1)
# Assuming 2 treatment and 2 controls
groups <- factor(c(rep("TGroup",2),rep("CGroup",2)))
sampleInfo <- data.frame(groups,row.names=colnames(data))
library(DESeq2, quietly=T)
dds <- DESeqDataSetFromMatrix(countData = data, colData = sampleInfo, design = ~ groups)
dds$condition = relevel(dds$groups,"CGroup")
dds <- DESeq(dds)
res <- results(dds,independentFiltering=F)
write.table(res, file="pairedEnd_test_gene_TE_analysis.txt", sep="\t",quote=F)
resSig <- res[(!is.na(res$padj) & (res$padj < 0.050000), ]
write.table(resSig, file="pairedEnd_test_sigdiff_gene_TE.txt",sep="\t", quote=F) 
```

**Comment by retrogenomics** [comment]
Thanks for your help.
-Gael
