### ISSUE TITLE
Stranded libraries

### ISSUE THREAD

**Issue by retrogenomics** [mhammell-laboratory/tetoolkit#31]
Hi,

We generally have stranded RNA-seq libraries and I use the `--stranded yes`option, but I'm wondering if strand is actually used for TE counts. I have cases where a TE is inserted in the 3'UTR of a transcript, in opposite orientation. This gene is strongly upregulated and the TE too...

I can't be 100% sure that this is the cause, since I don't know from which loci the TE count comes from, but it looks very suspicious.

Also I'm wondering what `--strand` option should be used for stranded mRNA TruSeq libraries (yes or reverse? This is sometimes a bit ambigous (see [here](https://github.com/igordot/genomics/blob/master/notes/rna-seq-strand.md)).

Thank you in advance for your help
-Gael

**Comment by olivertam** [comment]
Hi Gael,

For TruSeq libraries, the `--strand reverse` option should be used.

Cheers,
Oliver

**Comment by retrogenomics** [comment]
Thanks Oliver, indeed that was the problem.

**Comment by xiaocong3333** [comment]
I'm also confused about, for stranded mRNAseq, the -strand(yes/reverse), how should I use. I use yes and reverse separately, and the result of sigdiff gene and TE is totally different. 
In which situation, should I use yes or reverse?

Thank you in advance for your help!
Cong

**Comment by olivertam** [comment]
Hi Cong,

Depending on how your library is constructed, the sequenced read (read 1 in paired-end libraries) is either in the same orientation (sense) as the mRNA transcript (`--stranded yes`), or in the opposite orientation (antisense) as the mRNA transcript (`--stranded reverse`).
If you are using the [Illumina TruSeq stranded mRNA kit](https://www.illumina.com/products/by-type/sequencing-kits/library-prep-kits/truseq-stranded-mrna.html), they usually generate libraries where the sequenced read is in the antisense orientation. Thus you would choose `--stranded reverse`

See also HTSeq-count's description, which we based our parameter on:
> -s <yes/no/reverse>, --stranded=<yes/no/reverse>
>     For stranded=no, a read is considered overlapping with a feature regardless of whether it is mapped to the same or the opposite strand as the feature. For stranded=yes and single-end reads, the read has to be mapped to the same strand as the feature. For paired-end reads, the first read has to be on the same strand and the second read on the opposite strand. For stranded=reverse, these rules are reversed.

Please let me know if you have further questions.
Thanks

**Comment by xiaocong3333** [comment]
Thank you! Your suggestions are very helpful!
