### ISSUE TITLE
Documentation for reformatting TE GTF file

### ISSUE THREAD

**Issue by AlicePsyche** [mhammell-laboratory/tetoolkit#32]
Hi, 

Sorry for the interruption. I just want to know if there is any guideline for reformatting downloaded UCSC TE GTF file? I found the discussion [here](https://github.com/mhammell-laboratory/tetoolkit/issues/6) and [here](https://github.com/mhammell-laboratory/tetoolkit/issues/21) but it seems that they are not the full rules? For example, for the danRer10, there are 3565006 lines in the rmsk.txt table from UCSC but only 2548675 in your [provided GTF file](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEToolkit/TE_GTF/). So what should I do if I want to deal with other organism TE GTF file? (I have to use danRer7, the file is [here](https://www.dropbox.com/s/50u6mwvtd7739nc/danRer7_rmsk_anno.txt.zip?dl=0) )

Thanks for your help in advance!

Best,
Alice

**Comment by olivertam** [comment]
Hi Alice,

One filter that we do is to remove structural RNA (e.g. rRNA, scRNA, snRNA, srpRNA, tRNA) and simple repeat/low complexity regions (e.g. (TG)n repeats), as we do not consider them as transposable elements. I think that would account for the differences in numbers.
A parsed version of the TE GTF for danRer7 is available (using your file as input) [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEToolkit/TE_GTF/danRer7_rmsk_TE.gtf.gz). 
Let me know if you are still encountering issues with reformatting or with the provided GTF
Thanks.

Cheers,
Oliver

**Comment by AlicePsyche** [comment]
Many thanks for the prompt reply and the ready-to-use GTF file! Really helps me a lot.

**Comment by GlastonburyC** [comment]
Do any of these filtered GTFs for TEs exist? Because all the links fail for me.

**Comment by olivertam** [comment]
Hi,

Yes, they exist. Unfortunately, our server might be down right now.
We'll post here again once they are up.

Thanks.

**Comment by olivertam** [comment]
Hi,

The server should be back up now.
Please let us know if you have any more issues.

Thanks.

**Comment by olivertam** [comment]
Hi,

The server is back up, and the files should now be accessible.

Thanks for letting us know.

**Comment by shanshan-yin** [comment]
Hey, the files are unaccessible now again..anyone could help? I need annotation for mouse TEs..

**Comment by olivertam** [comment]
Hi,

We are having some server issue. We are temporarily hosting files on Dropbox at the following [link](https://www.dropbox.com/sh/1ppg2e0fbc64bqw/AACUXf-TA1rnBIjvykMH2Lcia?dl=0).
Please let us know if you are still having issues accessing the files.

Thanks.
