### ISSUE TITLE
No comments in TE.gtf allowed

### ISSUE THREAD

**Issue by foriin** [mhammell-laboratory/tetoolkit#36]
Hi! It seems like TEtranscripts fails to generate TE index if there are comments in TE.gtf file. Could you please fix that?

**Comment by olivertam** [comment]
Hi,
Would you be able to provide a copy (or a truncated version) of the TE GTF file that you're using?
Was this file generated by us, with comments added afterwards, or generated by you (or another user)?
Thanks.

**Comment by olivertam** [comment]
Hi,

I have made a small fix that might be able to address your issue.
If you don't mind re-installing TEtoolkit, either by downloading the ZIP (clicking the clone or download button), or cloning the repository (`git clone https://github.com/mhammell-laboratory/tetoolkit.git`), you might be able to get it working with your commented TE GTF files.

Thanks.

**Comment by foriin** [comment]
> Hi,
> Would you be able to provide a copy (or a truncated version) of the TE GTF file that you're using?
> Was this file generated by us, with comments added afterwards, or generated by you (or another user)?
> Thanks.

Sorry it took so long. I used a file from your collection and added simple comment starting with a '#' on a first line. Hope it's resolved in your fix :)
Thank you

**Comment by olivertam** [comment]
Resolved by commit 3754ac9871e47b7814325ffc1725dadc4b616c73
