### ISSUE TITLE
DESeq error

### ISSUE THREAD

**Issue by CodyS5** [mhammell-laboratory/tetoolkit#37]
Hello, 

When working with a single control and multiple treatments, I get clean output from TEtranscripts. However, when working with a single treatment bam and a single control bam I get the following error message from DESeq2: 

estimating size factors
estimating dispersions
Error in checkForExperimentalReplicates(object, modelMatrix) : 

  The design matrix has the same number of samples and coefficients to fit,
  so estimation of dispersion is not possible. Treating samples
  as replicates was deprecated in v1.20 and no longer supported since v1.22.

Calls: DESeq ... estimateDispersions -> .local -> checkForExperimentalReplicates
Execution halted
INFO  : Done 

Is there a work around for this, or do you have any recommendations? My data is moving through time points, so ideally I would be able to compare each new timepoint to the last. 

Thank you.

**Comment by olivertam** [comment]
Hi,

Unfortunately, this is a limitation put in place by DESeq2 as of version 1.22.0 (see [here](https://bioconductor.org/packages/release/bioc/news/DESeq2/NEWS)). A possible workaround is to use an older version of DESeq2 (as the error message indicates, treating samples as replicates is no longer supported in v1.22, so version <=1.21 should at least handle it).
It might also be worth raising this question to the authors of DESeq2 to see if they have any recommendations on how best to address this issue.
Thanks.

**Comment by CodyS5** [comment]
I kind of figured that might be the best way around it, but I thought I'd ask in case you had seen this before. Thank you for the help!
