### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by olferievm** [mhammell-laboratory/tetoolkit#38]
Dear Author.

I used the following way to install TEToolkit:
`~$ sudo pip3 install TEToolkit`

When run got the next issue:

```
~$ TEtranscripts
  File "/usr/local/bin/TEtranscripts", line 306
    avgReadLength += abs(pos1-pos2)+read2.query_length
                                                 ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by olivertam** [comment]
Hi,

It looks like you're installing TEToolkit with python3. Unfortunately, this python version has not been tested, and thus not currently supported.
We would recommend using python 2.7.x with TEtoolkit.

Thanks.

**Comment by olferievm** [comment]
Thank you for the fast reply. Will try now.

**Comment by olferievm** [comment]
And now it works. Thank you!
