### ISSUE TITLE
Using TCGA bam files

### ISSUE THREAD

**Issue by ge2sasag** [mhammell-laboratory/tetoolkit#39]
Hi,

I wonder if there is any way to read TCGA bam files and analyze them with TEtranscripts without need of downloading. I'm not sure if I could skip the downloading step due to the space requirements.

Any help is very much appreciated.

Gema

**Comment by olivertam** [comment]
Hi Gema,

Thank you for your interest in the software. Unfortunately, there is no simple way to access TCGA BAM files without downloading (especially with the controlled access associated with that project).

An alternative strategy is to download small batches of BAM at a time, and run TEcount on each of the individual BAM files. You can then delete the downloaded BAM once TEcount is completed, which will save on space. Once all your desired libraries are processed, you can combine them into a single counts table and run your differential analysis  using DESeq2 (which is what is used by TEtranscripts).

Please let me know if there are any questions.
Thanks.

Cheers,
Oliver
